=== stfc-aeg/lpd-detector/app/lpd/LpdFemClient/tests/lpdCommandSequence.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="lpd_command_sequence">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="clear_skip_register"/>
                <xs:element ref="nop"/>
                <xs:element ref="on_chip_reset_disable"/>
                <xs:element ref="read_out_data"/>
                <xs:element ref="reset_gain_back"/>
                <xs:element ref="reset_gain_front"/>
                <xs:element ref="reset_pre_amp"/>
                <xs:element ref="reset_state_machine"/>
                <xs:element ref="reset_trigger_pointer"/>
                <xs:element ref="reset_write_pointer"/>
                <xs:element ref="stand_by"/>
                <xs:element ref="start_trigger_pointer"/>
                <xs:element ref="start_write_pointer"/>
                <xs:element ref="stop_read_out"/>
                <xs:element ref="stop_readout"/>
                <xs:element ref="sync_reset"/>
                <xs:element ref="trigger_flag_set"/>
                <xs:element ref="loop"/>
            </xs:choice>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="clear_skip_register">
        <xs:complexType/>
    </xs:element>
    <xs:element name="nop">
        <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                <xs:element ref="clear_skip_register"/>
                <xs:element ref="nop"/>
                <xs:element ref="on_chip_reset_disable"/>
                <xs:element ref="read_out_data"/>
                <xs:element ref="reset_gain_back"/>
                <xs:element ref="reset_gain_front"/>
                <xs:element ref="reset_pre_amp"/>
                <xs:element ref="reset_state_machine"/>
                <xs:element ref="reset_trigger_pointer"/>
                <xs:element ref="reset_write_pointer"/>
                <xs:element ref="stand_by"/>
                <xs:element ref="start_trigger_pointer"/>
                <xs:element ref="start_write_pointer"/>
                <xs:element ref="stop_read_out"/>
                <xs:element ref="stop_readout"/>
                <xs:element ref="sync_reset"/>
                <xs:element ref="trigger_flag_set"/>
                <xs:element ref="loop"/>
            </xs:choice>
            <xs:attribute name="count" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="on_chip_reset_disable">
        <xs:complexType/>
    </xs:element>
    <xs:element name="read_out_data">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_gain_back">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_gain_front">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_pre_amp">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_state_machine">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_trigger_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_write_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stand_by">
        <xs:complexType/>
    </xs:element>
    <xs:element name="start_trigger_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="start_write_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stop_read_out">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stop_readout">
        <xs:complexType/>
    </xs:element>
    <xs:element name="sync_reset">
        <xs:complexType/>
    </xs:element>
    <xs:element name="trigger_flag_set">
        <xs:complexType/>
    </xs:element>
    <xs:element name="loop">
    	<xs:complexType/>
    </xs:element>
</xs:schema>

=== stfc-aeg/lpd-detector/app/lpd/LpdFemTests/ConfigFiles/asic_pseudo_random_asicv2.xml
<?xml version="1.0"?>
<lpd_command_sequence name="AutoResets_ShortExposures_AsicControl.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- For Pseudo random data from asic  jac 
         asic simply starts outputting pseudorandom data as soon as test_mode_d received
         Nb must not send start readout to asic or messes up subsequent runs
         so must relay on a fixed delay for asicrx start strobe
		 therefore changing the relative start position of test_mode_d will change the timing of capture
         cmds copied from fast_random_gaps.txt
     -->

	<nop/>
	<sync_reset/>
	<nop/>
	<!--reset_state_machine/>
	<nop/>
	<asic_slow_readout_start/
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/-->
	<nop/>
	<test_mode_d/>
	<nop/>
	<nop/>
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) -->
	<loop count="4">
		<nop/>
		<nop count="838"/>
	</loop>
	<!--stop_read_out/-->
	<reset_state_machine/>

</lpd_command_sequence>

=== stfc-aeg/lpd-detector/config/CmdSequence/LPD_cmdSeq_NormalOperation.xml
<?xml version="1.0"?>
<lpd_command_sequence name="LPD_cmdSeq_NormalOperation.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

	<!-- template created and tested by P. Lang, only to be used for v2 ASICs -->

	<nop/>
	<sync_reset/> <!-- Start Config chip -->
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/> 
	<nop/>
	<on_chip_reset_enable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<nop/>

	<start_write_pointer/>
	<start_trigger_pointer/> 
	<nop/>
    <!--<trigger_flag_set count="32"/>get from Karabo -->  <!-- moved by jac -->
	
        <trigger_section>
	</trigger_section>

	<reset_write_pointer/>
	<reset_trigger_pointer/>

	<on_chip_reset_disable/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<!--<nop count="4"/>--> <!--excluded 10.2.16 PL-->
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/> 
	<!-- Add additional NOPS to allow sufficient data to be clocked out of the ASICs -->
	<loop count="512"><!-- for 512 images -->
		<nop/>
		<nop count="850"/>
	</loop>
	<nop/>
	<stop_read_out/>
    <nop count="33"/>
    <nop/>
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/app/lpd/LpdFemTests/Config/CmdSequence/Command_LongExposure_legacy_using_trigger_flags_multiple_gain_readout.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure_legacy_using_trigger_flags_multiple_gain_readout.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 
         
        See also LPD FEM Firmware Description document.

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus a few extra

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

		for asic v2 so no slow clock for readout
    
    New CCC module Fast command Start sequence

    -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
    <nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
    <reset_gain_back/>
    <nop/>
    <start_write_pointer/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
    <!-- add a delay so that image in 1st cell is a long exposure -->
    <!--loop count="1">  
        <nop/>
        <nop count="1024"/>
    </loop>    
    <start_write_pointer/>
    <nop/-->
    <start_trigger_pointer/> 
    <!-- Add single NOP after <start_trigger_pointer> before the trigger_section 
        as Trigger Pointer starts at location -1 which doesn't exist.
        See LPD ASIC manual. There is some detail on page 48 and 49
        This is so that 1st veto mask bit will flag 1st memory pipeline location 
        Needed for correct pipeline emulation.
        Dec 2015    John C  
    -->
    <nop/>
    <!-- Test Legacy operation sending Trigger_Flags for special tests.
         Sends arbitrary asic commands and trigger flags during the setup phase.
         In addition:
         To suppress triggers from nvetos set default for Veto Pattern Mask words = $ffffffff in veto_pattern_mask.xml  
         Set the number of images in readout by Karabo parameter "numberImages"
         AND ignore nvetos by setting Karabo parameter  "cccProvideNumberImages" = FALSE 
          -->
    <trigger_flag_set/>
    <nop count="600"/>
    <trigger_flag_set/>
    <trigger_flag_set/>

    <!-- end of setup commands -->    
    <nop/>
	<trigger_section>
    <!-- NB trigger section contents are ignored by f/w 02ac and later -->
	</trigger_section>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>
	<nop/>
	<sync_reset/>
	<nop/>
    
    
    <!-- 
         1st Readout Gain x100
         -->
    <nop/>    
    <force_gain_x100/>   <!-- need a single nop before this command -->
    <nop/>  
    <sync_reset/>   <!-- need a single nop before this command -->
    <nop/>  
    <read_out_data/>   <!-- need a single nop before this command -->
    
    <nop count="36"/>  <!-- Fixed offset to account for delay between sending of read_out_data command and arrival of serial data from asic ~ 805 clocks -->  
    
    <loop count="3">     <!-- 1 loop per image to readout -->
        <nop count="837"/>
    </loop>
    <!-- 
         2nd Readout Gain x10
         -->
    <nop/>    
    <force_gain_x10/>    <!-- need a single nop before this command -->
    <loop count="3">  <!-- 1 loop per image to readout -->
        <nop count="837"/>
    </loop>
    <!-- 
         3rd Readout Gain x1
         -->
    <nop/>   
    <force_gain_x1/>   <!-- need a single nop before this command -->
    <loop count="3">   <!-- 1 loop per image to readout -->
        <nop/>
        <nop count="837"/>
    </loop>
    <nop/>    
    <stop_read_out/>   <!-- need a single nop before this command -->
    <!-- 
         End
         -->
  
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/app/lpd/LpdFemTests/ConfigFiles/asic_pseudo_random_asicv1.xml
<?xml version="1.0"?>
<lpd_command_sequence name="AutoResets_ShortExposures_AsicControl.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- For Pseudo random data from asic  jac 
         asic simply starts outputting pseudorandom data as soon as test_mode_d received
         asic ignores read_out_data cmd but it is still needed to trigger fem readout
         note that read_out_data cmd needs to come before test_mode_d to be ready for start of data
         as usual need a single nop before sync_reset, read_out_data and asic_slow_readout_start cmds.
     -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<asic_slow_readout_start/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/>
	<nop/>
	<test_mode_d/>
	<nop/>
	<nop/>
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) -->
	<loop count="4">
		<nop/>
		<nop count="838"/>
	</loop>
	<reset_state_machine/>

</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/ConfigFiles/superModRandomData.xml
<?xml version="1.0"?>
<lpd_command_sequence name="superModRandomData.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

	<sync_reset/> <!-- Start Config chip -->
	<nop/>
	<reset_state_machine/>
	<sync_reset/>
	<test_mode_d/>	
	<nop count="4"/>
	<asic_slow_readout_start/>
	<nop count="4"/>
	<sync_reset/>
	<nop/>
	<read_out_data/> 
	<!-- Add additional NOPS to allow sufficient data to be clocked out of the ASICs -->
	<loop count="11">
		<nop/>
		<nop count="501"/>
	</loop>
	<nop/>
	<reset_state_machine/>
	<nop/>
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/Config/CmdSequence/Command_LongExposure_Start_and_Stop_with_trigger_section.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure_Start_and_Stop_with_trigger_section.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus a few extra

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

		for asic v2 so no slow clock for readout
    
    New CCC module Fast command Start sequence

    -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
    <start_write_pointer/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
    <start_trigger_pointer/> 
    <!-- Add single NOP after <start_trigger_pointer> before the trigger_section 
        as Trigger Pointer starts at location -1 which doesn't exist.
        See LPD ASIC manual. There is some detail on page 48 and 49
        This is so that 1st veto mask bit will flag 1st memory pipeline location 
        Needed for correct pipeline emulation.
        Dec 2015    John C  
    -->
    <nop/>
	<trigger_section>
    <!-- Trigger section must be present for f/w 02ac and later -->
    <!-- It marks the position where C&C Veto Information will be inserted into the command sequence -->
    <!-- NB Any COMMANDS including <trigger_flag_set> found in this section will be IGNORED  -->
    <trigger_flag_set/>
    <nop count="5"/>
    <trigger_flag_set/>
    <nop count="5"/>
    <trigger_flag_set/>
    <nop count="5"/>
	  <trigger_flag_set/>
	</trigger_section>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/>
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) -->
	<loop count="420">  <!-- 511 images -->
		<nop/>
		<nop count="1023"/>
	</loop>
	<stop_read_out/>
	<nop count="33"/>
	<nop/>
  
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/Config/CmdSequence/Command_LongExposure_legacy_using_trigger_flags_modified.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure_legacy_using_trigger_flags.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- template created and tested by P. Lang, only to be used for v2 ASICs -->

    <nop/>
    <sync_reset/> <!-- Start Config chip -->
    <nop/>
    <reset_state_machine/>
    <nop/>
    <on_chip_reset_enable/>
    <nop/>
    <reset_write_pointer/>
    <reset_trigger_pointer/>
    <clear_skip_register/>
    <nop/><!--new 10.2.16 PL-->
    <start_write_pointer/>
    <nop/>
    <start_trigger_pointer/> 
    <nop/>
    
    <trigger_section>    
    <trigger_flag_set/>
    <trigger_flag_set/>
    <nop count="600"/>
    <trigger_flag_set/>
    <trigger_flag_set/>
    <!-- end of setup commands -->    
    </trigger_section>
    <reset_write_pointer/>
    <reset_trigger_pointer/>
    
    <on_chip_reset_disable/>
    <reset_pre_amp/>
    <reset_gain_front/>
    <reset_gain_back/>
    <!--<nop count="4"/>--> <!--excluded 10.2.16 PL-->
    <nop/>
    <sync_reset/>
    <nop/>
	<read_out_data/>
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) -->
	<loop count="32">  <!-- 511 images -->
		<nop/>
		<nop count="850"/>
	</loop>
    <nop/>
	<stop_read_out/>
	<nop count="33"/>
	<nop/>  
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/Config/CmdSequence/Command_LongExposure_what.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure_what.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough <nop/>s to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 <nop/>s per image (512 pixels x 3 x 12 bits) plus allow extra 1000 <nop/>s for offset from readout cmd to start of asic header

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE
    -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<start_write_pointer/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
	<start_trigger_pointer/> 
	<nop count="4"/>
	<trigger_flag_set/>
	<nop count="9"/>
	<trigger_flag_set/>
	<nop count="9"/>
	<trigger_flag_set/>
	<nop count="9"/>
	<trigger_flag_set/>
	<nop count="2"/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<asic_slow_readout_start/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/>
	<loop count="6">
		<nop count="840"/>
	</loop>
	<nop count="1000"/>
	<stop_read_out/>
	<nop count="33"/>
	
	<!-- Matt's command sequence configuration:
	Command Sequence
	Manual Resets â€“ Long Exposure
	Part 1 (100MHz)
	Sync Reset
	NOP
	Reset SM
	Sync Reset
	NOP
	On chip rst dis
	NOP
	Rst write ptr
	Rst trig ptr
	Clr skip reg
	NOP
	Rst preamp
	Rst gain front
	Rst gain back
	Rem rst preamp
	Rem rst gain st1
	Rem rst gain st2
	Start trig ptr
	NOPx4
	Trig flag set
	NOPx9
	Trig flag set
	NOPx9
	Trig flag set
	NOPx9
	Trig flag set
	NOPx2
	Rst preamp
	Rst gain front
	Rst gain back
	Rst write ptr
	Rst trig ptr
	NOP
	Asic slow readout
	Part 2 (6MHz)
	NOP
	Sync reset
	NOP
	Read out data
	NOP x 3500
	Stop read out
	NOP x 33
	-->
</lpd_command_sequence>
