=== stfc-aeg/lpd-detector/app/lpd/LpdFemClient/tests/lpdCommandSequence.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="lpd_command_sequence">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="clear_skip_register"/>
                <xs:element ref="nop"/>
                <xs:element ref="on_chip_reset_disable"/>
                <xs:element ref="read_out_data"/>
                <xs:element ref="reset_gain_back"/>
                <xs:element ref="reset_gain_front"/>
                <xs:element ref="reset_pre_amp"/>
                <xs:element ref="reset_state_machine"/>
                <xs:element ref="reset_trigger_pointer"/>
                <xs:element ref="reset_write_pointer"/>
                <xs:element ref="stand_by"/>
                <xs:element ref="start_trigger_pointer"/>
                <xs:element ref="start_write_pointer"/>
                <xs:element ref="stop_read_out"/>
                <xs:element ref="stop_readout"/>
                <xs:element ref="sync_reset"/>
                <xs:element ref="trigger_flag_set"/>
                <xs:element ref="loop"/>
            </xs:choice>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="clear_skip_register">
        <xs:complexType/>
    </xs:element>
    <xs:element name="nop">
        <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                <xs:element ref="clear_skip_register"/>
                <xs:element ref="nop"/>
                <xs:element ref="on_chip_reset_disable"/>
                <xs:element ref="read_out_data"/>
                <xs:element ref="reset_gain_back"/>
                <xs:element ref="reset_gain_front"/>
                <xs:element ref="reset_pre_amp"/>
                <xs:element ref="reset_state_machine"/>
                <xs:element ref="reset_trigger_pointer"/>
                <xs:element ref="reset_write_pointer"/>
                <xs:element ref="stand_by"/>
                <xs:element ref="start_trigger_pointer"/>
                <xs:element ref="start_write_pointer"/>
                <xs:element ref="stop_read_out"/>
                <xs:element ref="stop_readout"/>
                <xs:element ref="sync_reset"/>
                <xs:element ref="trigger_flag_set"/>
                <xs:element ref="loop"/>
            </xs:choice>
            <xs:attribute name="count" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="on_chip_reset_disable">
        <xs:complexType/>
    </xs:element>
    <xs:element name="read_out_data">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_gain_back">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_gain_front">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_pre_amp">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_state_machine">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_trigger_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_write_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stand_by">
        <xs:complexType/>
    </xs:element>
    <xs:element name="start_trigger_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="start_write_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stop_read_out">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stop_readout">
        <xs:complexType/>
    </xs:element>
    <xs:element name="sync_reset">
        <xs:complexType/>
    </xs:element>
    <xs:element name="trigger_flag_set">
        <xs:complexType/>
    </xs:element>
    <xs:element name="loop">
    	<xs:complexType/>
    </xs:element>
</xs:schema>

=== stfc-aeg/lpd-detector/app/lpd/LpdFemTests/ConfigFiles/short_exposure_all_3gains_asicv2_B.xml
<?xml version="1.0"?>
<lpd_command_sequence name="short_exposures_all_3gains_asicv2.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Example lpd command sequence  jac 

        File for reading out ALL 3 gains.  Needs f/w vers 0134 or later.
        One usual cycle of SHORT exposure triggers then readout is repeated 3 times, once for each gain.
        Uses new dummy Fast commands to switch gain select and controlling asic rx logic.
        This overrides gain selection from register.

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus a few extra

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

		for asic v2 so no slow clock for readout

    -->
<!-- comment -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_enable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<start_write_pointer/>
	<nop/>
	<nop/>
	<start_trigger_pointer/> 
	<nop/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<nop/>
	<nop/>
	<on_chip_reset_disable/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>

<!-- 
     Readout Sequences with differnet Gain Selections
-->

	<nop/>    
	<force_gain_x100/>   <!-- need a single nop before this command -->
	<nop/>  
	<sync_reset/>   <!-- need a single nop before this command -->
	<nop/>  
	<read_out_data/>   <!-- need a single nop before this command -->
  <nop count="35"/>  <!-- Fixed Latency before start of asic data arriving at FEM -->  
	<loop count="1">     <!-- 1 loop per image to readout -->
		<nop count="836"/>
	</loop>
<!-- 
     
-->
	<nop/>    
	<force_gain_x10/>    <!-- need a single nop before this command -->
	<loop count="1">  <!-- 1 loop per image to readout -->
		<nop count="836"/>
	</loop>
<!-- 
     
-->
	<nop/>    
	<force_gain_x100/>    <!-- need a single nop before this command -->
	<loop count="1">  <!-- 1 loop per image to readout -->
		<nop count="836"/>
	</loop>
<!-- 
     
-->
	<nop/>   
	<force_gain_x10/>   <!-- need a single nop before this command -->
	<loop count="1">   <!-- 1 loop per image to readout -->
		<nop/>
		<nop count="836"/>
	</loop>
	<nop/>    
	<stop_read_out/>   <!-- need a single nop before this command -->
<!-- 
      End
-->
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/ConfigFiles/playingWivLasers.xml
<?xml version="1.0"?>
<lpd_command_sequence name="playingWivLasers.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus allow extra 1000 nops for offset from readout cmd to start of asic header

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

    -->

	<sync_reset/> <!-- Start Config chip -->
	<nop/>
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<start_write_pointer/>
	<start_trigger_pointer/> 
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
	<nop count="3"/>
	<loop count="5">
	    <trigger_flag_set/>
	    <!--nop count="1"/-->
	</loop>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>	
	<nop count="4"/>
	<nop/>
	<asic_slow_readout_start/>
	<nop count="4"/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/> 
	<!-- Add additional NOPS to allow sufficient data to be clocked out of the ASICs -->
	<loop count="5">
		<nop/>
		<nop count="840"/>
	</loop>
	<nop count ="1000"/>
	<nop/>
	<reset_state_machine/>
	<nop/>
</lpd_command_sequence>
