=== stfc-aeg/lpd-detector/app/lpd/LpdFemClient/tests/lpdCommandSequence.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="lpd_command_sequence">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="clear_skip_register"/>
                <xs:element ref="nop"/>
                <xs:element ref="on_chip_reset_disable"/>
                <xs:element ref="read_out_data"/>
                <xs:element ref="reset_gain_back"/>
                <xs:element ref="reset_gain_front"/>
                <xs:element ref="reset_pre_amp"/>
                <xs:element ref="reset_state_machine"/>
                <xs:element ref="reset_trigger_pointer"/>
                <xs:element ref="reset_write_pointer"/>
                <xs:element ref="stand_by"/>
                <xs:element ref="start_trigger_pointer"/>
                <xs:element ref="start_write_pointer"/>
                <xs:element ref="stop_read_out"/>
                <xs:element ref="stop_readout"/>
                <xs:element ref="sync_reset"/>
                <xs:element ref="trigger_flag_set"/>
                <xs:element ref="loop"/>
            </xs:choice>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="clear_skip_register">
        <xs:complexType/>
    </xs:element>
    <xs:element name="nop">
        <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                <xs:element ref="clear_skip_register"/>
                <xs:element ref="nop"/>
                <xs:element ref="on_chip_reset_disable"/>
                <xs:element ref="read_out_data"/>
                <xs:element ref="reset_gain_back"/>
                <xs:element ref="reset_gain_front"/>
                <xs:element ref="reset_pre_amp"/>
                <xs:element ref="reset_state_machine"/>
                <xs:element ref="reset_trigger_pointer"/>
                <xs:element ref="reset_write_pointer"/>
                <xs:element ref="stand_by"/>
                <xs:element ref="start_trigger_pointer"/>
                <xs:element ref="start_write_pointer"/>
                <xs:element ref="stop_read_out"/>
                <xs:element ref="stop_readout"/>
                <xs:element ref="sync_reset"/>
                <xs:element ref="trigger_flag_set"/>
                <xs:element ref="loop"/>
            </xs:choice>
            <xs:attribute name="count" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="on_chip_reset_disable">
        <xs:complexType/>
    </xs:element>
    <xs:element name="read_out_data">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_gain_back">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_gain_front">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_pre_amp">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_state_machine">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_trigger_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="reset_write_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stand_by">
        <xs:complexType/>
    </xs:element>
    <xs:element name="start_trigger_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="start_write_pointer">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stop_read_out">
        <xs:complexType/>
    </xs:element>
    <xs:element name="stop_readout">
        <xs:complexType/>
    </xs:element>
    <xs:element name="sync_reset">
        <xs:complexType/>
    </xs:element>
    <xs:element name="trigger_flag_set">
        <xs:complexType/>
    </xs:element>
    <xs:element name="loop">
    	<xs:complexType/>
    </xs:element>
</xs:schema>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/Config/CmdSequence/Command_LongExposure_V2.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure_V2.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus a few extra

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

		for asic v2 so no slow clock for readout

    -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<start_write_pointer/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
	<start_trigger_pointer/> 
	<nop count="30"/>
	<trigger_flag_set/>
	<nop count="10"/>
	<trigger_flag_set/>
	<nop count="10"/>
	<trigger_flag_set/>
	<nop count="10"/>
	<trigger_flag_set/>
	<nop count="2"/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/>
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) -->
	<loop count="4">
		<nop/>
		<nop count="838"/>
	</loop>
    <nop count="30"/>   # one extra row
	<stop_read_out/>
	<nop count="33"/>
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/Config/CmdSequence/Command_ShortExposure_V2.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_ShortExposure_V2.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus a few extra

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

		for asic v2 so no slow clock for readout

    -->

	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_enable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<start_write_pointer/>
	<nop/>
	<nop/>
	<start_trigger_pointer/> 
	<nop/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<nop/>
	<nop/>
	<on_chip_reset_disable/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>
	<nop/>
	<!--nop/-->
	<sync_reset/>
	<nop/>
	<read_out_data/>
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) -->
	<loop count="4">
		<nop/>
		<nop count="838"/>
	</loop>
    <nop count="31"/>   # one extra row
	<stop_read_out/>
	<nop count="33"/>

	<!-- Matt's configuration:	
	Auto Resets â€“ Short Exposures
	Part 1 (100MHz)
	Sync Reset
	NOP
	Reset SM
	Sync Reset
	NOP
	On chip rst en
	NOP
	Rst write ptr
	Rst trig ptr
	Clr skip reg
	Start wrt ptr
	NOP
	NOP
	Start trig ptr
	NOP
	Trig flag set
	Trig flag set
	Trig flag set
	Trig flag set
	NOP
	NOP
	On chip rst dis
	Rst preamp
	Rst gain front
	Rst gain back
	Rst write ptr
	Rst trig ptr
	NOP
	Asic slow readout
	Part 2 (6MHz)
	NOP
	Sync reset
	NOP
	Read out data
	NOP x 3500
	Stop read out
	NOP x 33
	-->
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/app/lpd/LpdFemTests/ConfigFiles/long_exposure_all_3gains_asicv2_C.xml
<?xml version="1.0"?>
<lpd_command_sequence name="longExposure_all_3gains_asicv2_A.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        File for reading out ALL 3 gains.
        One usual cycle of long exposure triggers then readout is repeated 3 times, once for each gain.
        Uses new dummy Fast commands to switch gain select and controlling asic rx logic.
        This overrides gain selection from register.
    
        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> , <stop_read_out/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        836 NOPs per image (512 pixels x 3 x 12 bits) plus a few extra

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

		for asic v2 so no slow clock for readout

    -->

	<nop/>  
	<sync_reset/>   <!-- need a single nop before this command -->
	<nop/>
	<reset_state_machine/>   <!-- need a single nop before this command -->
	<nop/>  
	<sync_reset/>
	<nop/>
	<on_chip_reset_disable/>  <!-- manual resets for long exposures -->
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<start_write_pointer/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
	<start_trigger_pointer/> 
	<nop count="20"/>
	<trigger_flag_set/>
	<nop count="2"/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>

<!-- 
     Readout Sequences with differnet Gain Selections
-->

	<nop/>    
	<force_gain_x100/>   <!-- need a single nop before this command -->
	<nop/>  
	<sync_reset/>   <!-- need a single nop before this command -->
	<nop/>  
	<read_out_data/>   <!-- need a single nop before this command -->

<!-- must allow for latency before 1st image only  -->
  <nop count="35"/>  <!-- Fixed Latency before start of asic data arriving at FEM -->  

<!-- now readout multiple images  -->

	<loop count="1">     <!-- 1 loop per image to readout -->
		<nop count="836"/>
	</loop>
<!-- 
     
-->
	<nop/>    
	<force_gain_x10/>    <!-- need a single nop before this command -->
	<loop count="1">  <!-- 1 loop per image to readout -->
		<nop count="836"/>
	</loop>
<!-- 
     
-->
	<nop/>    
	<force_gain_x1/>    <!-- need a single nop before this command -->
	<loop count="1">  <!-- 1 loop per image to readout -->
		<nop count="836"/>
	</loop>
<!-- 
     
-->
	<nop/>   
	<force_gain_x100/>   <!-- need a single nop before this command -->
	<loop count="1">   <!-- 1 loop per image to readout -->
		<nop/>
		<nop count="836"/>
	</loop>
	<nop/>    
	<stop_read_out/>   <!-- need a single nop before this command -->
<!-- 
      End
-->
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/ConfigFiles/fast_cmd_1f_with_slow_readout.xml
<?xml version="1.0"?>
<lpd_command_sequence name="fast_readout_replacement_commands.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">
	<!-- Replaces the file fast_readout_4f_gaps.txt -->
	
	<sync_reset/> <!-- Start Config chip? -->
	<on_chip_reset_enable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<start_write_pointer/>
	<start_trigger_pointer/> 
	<nop/>
    <nop count="51"/>
	<nop/>
	<trigger_flag_set count="1"/>
	<nop/>
	<on_chip_reset_disable/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>	
	<nop/>
	<asic_slow_readout_start/>	
	<nop/>
    <nop count="1001"/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/> 
	<nop/>
    <nop count="21"/>
	<!-- Add additional NOPS to allow sufficient data to be clocked out of the ASICs, loop count = nr of images -->
	<loop count="4">
		<nop/>
		<nop count="839"/>
	</loop>
 	<nop/>
    <nop count="21"/>
	<nop/>
	<reset_state_machine/>
	<nop/>
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemGui/config/CmdSequence/NoResets_MultiSample/LCLS_2018_Cmds_10images_NoReset_NoStagger.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure_V2.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 
         
         There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
         There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 
         
         The LAST command in the file must NOT be a <nop count="xx"/> as this causes state machine to loop the command sequence repeatedly
         
         For the readout phase add at least enough clock cycles (nops) to ensure all data is clocked out of the ASICs before <stop_read_out> or <reset_state_machine/> 
             
             Number clocks per Image = 512 pixels x 3 gain x 12 bits = 18,432        
             22 [4.5 MHz] => 837 nops per image approx    XFEL @ 99 MHz
             25 [4.0 MHz] => 737
             30 [3.3 MHz] => 614
             40 [2.5 MHz] => 460
             50 [2.0 MHz] => 368
   	   	  	100 [1.0MZ ] => 184
   	   	  	          
             Also add ~805 clocks FIXED offset to account for delay between <read_out_data> and arrival of first bit of data
                 22 [4.5 MHz] => 36 nops 
                 25 [4.0 MHz] => 32
                 30 [3.3 MHz] => 26
                 40 [2.5 MHz] => 20
                 50 [2.0 MHz] => 16
		 		100 [1.0MHz] => 8                   
    -->
                 
	<nop/>
	<sync_reset/>
	<nop/>
	<reset_state_machine/>
	<nop/>
	<sync_reset/>
	<nop/>
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<start_write_pointer/>
	<start_trigger_pointer/> 
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
	<nop/>	
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<trigger_flag_set/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<nop/>
	<nop/>
          
    <trigger_section>
    </trigger_section>

    <nop/>
    <sync_reset/>
    <nop/>
    <read_out_data/>
    <!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> -->
    <nop count="8"/>  <!-- Fixed offset to account for delay between sending of read_out_data command and arrival of serial data from asic ~ 805 clocks -->  
    <loop count="10">
        <nop/>
        <nop count="184"/>  <!-- typical value for div 22 = 837 -->
    </loop>
    <nop count="10"/>
    <nop/>
    <stop_read_out/>
    
    <nop/>  <!-- LAST command in the file must NOT be a <nop count="xx"/> -->

    <!-- 
         End
    --> 

</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdFemTests/Config/CmdSequence/Command_LongExposure.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Command_LongExposure.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

    <!-- Rules for lpd command sequence  jac 

        There MUST be a single <nop/> immediately before <sync_reset/>, <read_out_data/> and <asic_slow_readout_start/> 
        There MUST be exactly 1 <nop/> between <sync_reset/> and <read_out_data/> 

        For readout add enough nops to ensure all data is clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits) plus allow extra 1000 nops for offset from readout cmd to start of asic header

        If reading out V1 ASIC need  <asic_slow_readout_start/> in cmd sequence to slow clock during readout phase
        Must also set femAsicSlowedClock parameter in LpdReadoutTest.py to TRUE

    -->

	<nop/>
	<sync_reset/> <!-- Start Config chip -->
	<on_chip_reset_disable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<start_write_pointer/>
	<start_trigger_pointer/> 
	<nop/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<remove_reset_pre_amp/>
	<remove_reset_gain_stage1/>
	<remove_reset_gain_stage2/>
	<nop count="10"/>
	<trigger_section>
		<trigger_flag_set/>
		<nop count="10"/>
		<trigger_flag_set/>
		<nop count="10"/>
		<trigger_flag_set/>
		<nop count="10"/>
		<trigger_flag_set/>
	</trigger_section>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>	
 	<nop/>          <!-- There must be a <nop/> immediately before <asic_slow_readout_start/> -->
	<asic_slow_readout_start/>  <!-- This switches to slow clock during asic readout -->
	<nop/>          <!-- There must be a <nop/> immediately before <sync_reset/> -->
	<sync_reset/>
	<nop/>          <!-- There must be exactly 1 nop between <sync_reset/> and <read_out_data/>  -->
	<read_out_data/>   
	<!-- Add enough nops to allow all data to be clocked out of the ASICs before <reset_state_machine/> 
        840 NOPs per image (512 pixels x 3 x 12 bits)
         + allow 1000 NOPs for offset from readout cmd to start of asic header  -->
	<loop count="4">
		<nop/>
		<nop count="838"/>
	</loop>
	<nop count="1000"/>
	<nop/>
	<reset_state_machine/>
	<nop/>
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/python/src/LpdCommandSequence/fast_readout_replacement_commands.xml
<?xml version="1.0"?>
<lpd_command_sequence name="Replaces the first column in the file fast_readout_4f_gaps.txt"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

	<sync_reset/>
	<!-- Power down-->
	<stand_by/>
	<!--Command sequence to drive the 
	    state machine through the readout stages
	  -->
	
	<on_chip_reset_disable/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<start_write_pointer/>
	<start_trigger_pointer/>
	<trigger_flag_set/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<read_out_data nop="7"/> <!-- Enough NOPS to perform a few ADC conversions of the level on the PAD input -->
	<sync_reset nop="2"/> <!-- Return state machine to start write pointer -->
	<stop_read_out/>
	<!-- Alter the ADC pad input and start another conversion -->
	<start_trigger_pointer/>
	<trigger_flag_set/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<read_out_data nop="7"/>
	<sync_reset nop="2"/>
	<stop_read_out/>
	<reset_state_machine/>
	<nop/>
</lpd_command_sequence>

=== stfc-aeg/lpd-detector/app/lpd/tests/ConfigFiles/SuperModuleNormalOperation.xml
<?xml version="1.0"?>
<lpd_command_sequence name="SuperModuleNormalOperation.xml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="lpdCommandSequence.xsd">

	<sync_reset/> <!-- Start Config chip -->
	<nop/>
	<on_chip_reset_enable/>
	<nop/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>
	<clear_skip_register/>
	<start_write_pointer/>
	<start_trigger_pointer/> 
	<nop/>
	<nop/>
	<trigger_flag_set count="4"/><!-- 4 images saved from ASICs -->
	<nop/>
	<on_chip_reset_disable/>
	<reset_pre_amp/>
	<reset_gain_front/>
	<reset_gain_back/>
	<reset_write_pointer/>
	<reset_trigger_pointer/>

	<nop count="4"/>
	<nop/>
	<asic_slow_readout_start/>
	<nop count="4"/>
	<nop/>
	<sync_reset/>
	<nop/>
	<read_out_data/> 
	<!-- Add additional NOPS to allow sufficient data to be clocked out of the ASICs -->
	<loop count="11">
		<nop/>
		<nop count="501"/>
	</loop>
	<nop/>
	<reset_state_machine/>
	<nop/>
</lpd_command_sequence>
